# Generated by Django 4.0.5 on 2022-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande']},
        ),
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default='5000', max_length=200),
            preserve_default=False,
        ),
    ]
